# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026, Empa, James Allan, Reto Fricker

"""Seed mock content into each usecase workspace so every module has something
to show in local mode: an ontology extension, example SPARQL queries, sample
timeseries, and a private data product. All artifacts are prefixed `_mock_`
so they are easy to find and are gitignored locally (never committed).

Run against a usecases corpus (a directory of workspace folders):
    python tools/seed_mock_workspace_content.py <usecases_dir>
"""

from __future__ import annotations

import sys
from pathlib import Path

# keyword -> (component class, attr class local name, attr label, unit local name, theme)
THEMES = {
    "solar":      ("EnergyGenerator", "SolarIrradianceForecast", "Solar Irradiance Forecast", "W-PER-M2", "Solar"),
    "wind":       ("EnergyGenerator", "WindGustFactor",          "Wind Gust Factor",          "UNITLESS", "Wind"),
    "building":   ("EnergyConsumer",  "FlexibilityPotential",    "Flexibility Potential",     "KiloW",    "Building"),
    "ev":         ("EnergyConsumer",  "ChargingDemand",          "Charging Demand",           "KiloW",    "EV"),
    "heiloo":     ("Device",          "ControlSetpoint",         "Control Setpoint",          "DEG_C",    "Control"),
    "control":    ("Device",          "ControlSetpoint",         "Control Setpoint",          "DEG_C",    "Control"),
    "investa":    ("Storage",         "InvestmentHorizon",       "Investment Horizon",        "YR",       "Investment"),
    "price":      ("Actor",           "PriceForecastConfidence", "Price Forecast Confidence", "PERCENT",  "Price"),
    "congestion": ("Network",         "CongestionThreshold",     "Congestion Threshold",      "MegaW",    "Congestion"),
}
DEFAULT_THEME = ("Storage", "TechnologyReadinessLevel", "Technology Readiness Level", "UNITLESS", "Technology")


def theme_for(ws: str):
    low = ws.lower()
    for kw, t in THEMES.items():
        if kw in low:
            return t
    return DEFAULT_THEME


def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def extension_ttl(ws: str) -> str:
    comp, attr_cls, attr_label, unit, _ = theme_for(ws)
    return f"""@prefix dici_onto: <https://digicities.info/ontology#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

# Mock ontology extension for {ws} — generated by tools/seed_mock_workspace_content.py.
# Demonstrates a workspace-specific attribute class + object property in the
# dici_onto namespace. Not real domain content.

dici_onto:{attr_cls} a owl:Class ;
    rdfs:label "{attr_label}" ;
    rdfs:subClassOf dici_onto:PhysicalAttribute ;
    dici_onto:hasDefaultUnit <http://qudt.org/vocab/unit/{unit}> .

dici_onto:has{attr_cls} a owl:ObjectProperty ;
    rdfs:label "has {attr_label}" ;
    rdfs:domain dici_onto:{comp} ;
    rdfs:range dici_onto:{attr_cls} ;
    rdfs:subPropertyOf dici_onto:hasAttribute .
"""


def instance_ttl(ws: str, n: int = 2) -> str:
    comp, _, _, _, theme = theme_for(ws)
    base = f"https://digicities.info/proj/{ws}"
    lines = [
        "@prefix dici_onto: <https://digicities.info/ontology#> .",
        "@prefix qudt: <http://qudt.org/schema/qudt/> .",
        "@prefix unit: <http://qudt.org/vocab/unit/> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        "",
        f"# Mock data product instances for {ws}. Not real domain data.",
        "",
    ]
    for i in range(n):
        inst = f"<{base}/{comp}/Asset{i}>"
        rated = f"<{base}/{comp}/Asset{i}/RatedPower>"
        capex = f"<{base}/{comp}/Asset{i}/CAPEX>"
        lines += [
            f"{inst} a dici_onto:{comp} ;",
            f'\trdfs:label "{theme} Asset {i}" ;',
            f"\tdici_onto:hasAttribute {rated}, {capex} .",
            "",
            f"{rated} a dici_onto:StaticAttribute ;",
            f'\trdfs:label "Rated Power" ;',
            "\tqudt:unit unit:MegaW ;",
            f'\tqudt:value "{round(2.0 + i, 1)}"^^xsd:decimal .',
            "",
            f"{capex} a dici_onto:StaticAttribute ;",
            f'\trdfs:label "Capital Cost" ;',
            f'\tqudt:value "{2000000 * (i + 1)}"^^xsd:decimal .',
            "",
        ]
    return "\n".join(lines)


QUERIES = {
    "_mock_count_components_by_type.sparql": """PREFIX dici_onto: <https://digicities.info/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Count component instances by type.
SELECT ?type (COUNT(?i) AS ?count) WHERE {
  ?i a ?type .
  ?type rdfs:subClassOf* dici_onto:Component .
}
GROUP BY ?type
ORDER BY DESC(?count)
""",
    "_mock_attributes_with_values.sparql": """PREFIX dici_onto: <https://digicities.info/ontology#>
PREFIX qudt: <http://qudt.org/schema/qudt/>

# Every component attribute and its value (where present).
SELECT ?component ?attribute ?value WHERE {
  ?component dici_onto:hasAttribute ?attribute .
  OPTIONAL { ?attribute qudt:value ?value . }
}
ORDER BY ?component
LIMIT 200
""",
    "_mock_components_with_labels.sparql": """PREFIX dici_onto: <https://digicities.info/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# All components with their human-readable label.
SELECT ?instance ?label WHERE {
  ?instance a ?type ;
            rdfs:label ?label .
  ?type rdfs:subClassOf* dici_onto:Component .
}
ORDER BY ?label
""",
}


def timeseries_csv(ws: str) -> str:
    _, _, _, _, theme = theme_for(ws)
    rows = ["timestamp,value_MW"]
    # 24 hourly points, deterministic synthetic curve (no RNG — keep reproducible)
    for h in range(24):
        val = round(1.0 + 0.5 * ((h * 7) % 5), 3)
        rows.append(f"2026-01-01T{h:02d}:00:00Z,{val}")
    return "\n".join(rows) + "\n"


def main(corpus: Path) -> int:
    if not corpus.exists():
        print(f"corpus not found: {corpus}")
        return 2
    n = 0
    for ws_dir in sorted(p for p in corpus.iterdir() if p.is_dir()):
        ws = ws_dir.name
        if ws.startswith("."):
            continue
        _, _, _, _, theme = theme_for(ws)

        # 1. Ontology extension
        write(ws_dir / "ontology" / "extensions" / f"_mock_{ws}_extension.ttl", extension_ttl(ws))
        # 2. Query examples
        for fname, content in QUERIES.items():
            write(ws_dir / "queries" / fname, content)
        # 3. Sample timeseries
        write(ws_dir / "timeseries" / f"_mock_{theme.lower()}_generation.csv", timeseries_csv(ws))
        # 4. Private data product (folder with TTL + a resource file)
        prod = f"_mock_{theme}Catalog"
        write(ws_dir / "private_data_products" / prod / f"{prod}.ttl", instance_ttl(ws))
        write(ws_dir / "private_data_products" / prod / "resources" / "_mock_sample.csv", timeseries_csv(ws))

        n += 1
        print(f"seeded {ws}: extension + {len(QUERIES)} queries + timeseries + data product '{prod}'")
    print(f"\nDone. Seeded {n} workspaces.")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: python tools/seed_mock_workspace_content.py <usecases_dir>", file=sys.stderr)
        sys.exit(2)
    sys.exit(main(Path(sys.argv[1])))
