# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026, Empa, James Allan, Reto Fricker

"""Verify the workspace loader works end-to-end for every registered workspace.

For each workspace the registry discovers, this tool:

  1. Checks whether it has any instance / extension / scenario TTLs in the
     canonical locations the loader reads.
  2. (with --mock) If a workspace has no RDF at all, writes a small mock
     instance-data TTL into `ingestion/output/_mock_<id>.ttl` so the
     end-to-end path has something to load. Mock files are clearly prefixed
     with `_mock_` and can be removed with --clean-mocks.
  3. Runs `ensure_workspace_repo(ctx)` — the exact call the app makes on
     workspace open — provisioning the workspace's dataset in the active
     triplestore and loading its TTLs.
  4. SPARQL-counts components and attributes in the resulting dataset to
     confirm data actually landed and is queryable.

Prints a table and exits non-zero if any workspace failed to load or ended
up with zero queryable components.

Usage
-----
    # inside the running streamlit container (Fuseki reachable at fuseki:3030):
    python tools/verify_workspace_loading.py            # verify only
    python tools/verify_workspace_loading.py --mock     # inject mocks where empty, then verify
    python tools/verify_workspace_loading.py --clean-mocks   # remove injected mock files
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional

import requests

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from backend.triplestore import get_backend  # noqa: E402
from backend.workspace import ensure_workspace_repo, load_registry  # noqa: E402


MOCK_FILENAME = "ingestion/output/_mock_{id}.ttl"

# Canonical glob patterns the loader reads (see graphdb_provisioning.py).
INSTANCE_GLOBS = (
    "ontology/extensions/*.ttl",
    "ingestion/output/*.ttl",
    "scenarios/*.ttl",
)

# Concrete dici_onto classes that are subclasses of Component, picked by a
# keyword in the workspace id so the mock reads as thematically plausible.
# Every value here is a real class in services/graphdb/ontology/dici_onto_core.ttl.
THEME_BY_KEYWORD = {
    "solar": ("EnergyGenerator", "PV Array"),
    "wind": ("EnergyGenerator", "Wind Turbine"),
    "building": ("EnergyConsumer", "Building Load"),
    "ev": ("EnergyConsumer", "EV Charger"),
    "heiloo": ("Device", "Controller"),
    "control": ("Device", "Controller"),
    "investa": ("Storage", "Battery Bank"),
    "price": ("Actor", "Market Operator"),
    "congestion": ("Network", "Distribution Feeder"),
    "forecast": ("Resource", "Forecast Resource"),
}
DEFAULT_THEME = ("EnergyConsumer", "Generic Load")


def _theme_for(ws_id: str) -> tuple[str, str]:
    low = ws_id.lower()
    for kw, theme in THEME_BY_KEYWORD.items():
        if kw in low:
            return theme
    return DEFAULT_THEME


def _mock_ttl(ws_id: str) -> str:
    """Build a small, valid dici_onto instance graph for one workspace.

    Three components of a theme-appropriate Component subclass, each with two
    attributes carrying qudt:value literals — enough for the Digital Replica
    Explorer to render components and attributes.
    """
    cls, label = _theme_for(ws_id)
    base = f"https://digicities.info/proj/{ws_id}"
    lines = [
        "@prefix dici_onto: <https://digicities.info/ontology#> .",
        "@prefix qudt: <http://qudt.org/schema/qudt/> .",
        "@prefix unit: <http://qudt.org/vocab/unit/> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        "",
        f"# Mock instance data for {ws_id} — generated by tools/verify_workspace_loading.py.",
        "# Not real partner data. Remove with: python tools/verify_workspace_loading.py --clean-mocks",
        "",
    ]
    for i in range(3):
        inst = f"<{base}/{cls}/Unit{i}>"
        rated = f"<{base}/{cls}/Unit{i}/RatedPower>"
        cost = f"<{base}/{cls}/Unit{i}/CAPEX>"
        lines += [
            f"{inst} a dici_onto:{cls} ;",
            f'\trdfs:label "{label} {i}" ;',
            f"\tdici_onto:hasAttribute {rated}, {cost} .",
            "",
            f"{rated} a dici_onto:StaticAttribute ;",
            f'\trdfs:label "Rated Power" ;',
            "\tqudt:unit unit:MegaW ;",
            f'\tdici_onto:hasUnitLabel "MegaW"^^xsd:string ;',
            f'\tqudt:value "{round(1.5 + i, 1)}"^^xsd:decimal .',
            "",
            f"{cost} a dici_onto:StaticAttribute ;",
            f'\trdfs:label "Capital Cost" ;',
            f'\tqudt:value "{1000000 * (i + 1)}"^^xsd:decimal .',
            "",
        ]
    return "\n".join(lines)


def _has_instance_data(ctx) -> bool:
    for pat in INSTANCE_GLOBS:
        try:
            if ctx.storage.glob(pat):
                return True
        except Exception:
            pass
    return False


def _count(backend, dataset: str, sparql: str) -> Optional[int]:
    url = backend.query_url(dataset)
    try:
        r = requests.get(
            url,
            params={"query": sparql},
            headers={"Accept": "text/csv"},
            auth=getattr(backend, "auth", None),
            timeout=30,
        )
        r.raise_for_status()
    except requests.RequestException as exc:
        print(f"   query error on {dataset}: {exc}")
        return None
    lines = r.text.strip().splitlines()
    if len(lines) < 2:
        return None
    try:
        return int(lines[-1])
    except ValueError:
        return None


_PFX = (
    "PREFIX dici_onto: <https://digicities.info/ontology#> "
    "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> "
)

# Default-graph queries — what the Digital Replica Explorer (no GRAPH clause) sees.
COMPONENT_Q = _PFX + "SELECT (COUNT(DISTINCT ?i) AS ?n) WHERE { ?i a dici_onto:Component }"
ATTRIBUTE_Q = _PFX + "SELECT (COUNT(*) AS ?n) WHERE { ?i dici_onto:hasAttribute ?a }"

# Named-graph queries — exactly what the Replica Builder / Scenario Builder run.
# These guard against the "data in default graph but module reads a named graph"
# class of bug: if the loader stops populating these graphs, the count drops to
# 0 here even though the default-graph counts above stay green.
ONTOLOGY_GRAPH_Q = _PFX + (
    "SELECT (COUNT(DISTINCT ?c) AS ?n) WHERE { "
    "GRAPH <http://ontology_dici_onto> { ?c rdfs:subClassOf* dici_onto:Component } "
    "FILTER(?c != dici_onto:Component) }"
)


def clean_mocks(registry) -> int:
    removed = 0
    for ctx in registry:
        rel = MOCK_FILENAME.format(id=ctx.id)
        try:
            if ctx.storage.exists(rel):
                ctx.storage.delete(rel)
                print(f"removed {ctx.id}/{rel}")
                removed += 1
        except Exception as exc:
            print(f"could not remove mock for {ctx.id}: {exc}")
    print(f"\n{removed} mock file(s) removed.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mock", action="store_true",
                    help="inject a mock instance TTL into any workspace that has no RDF")
    ap.add_argument("--clean-mocks", action="store_true",
                    help="remove all _mock_*.ttl files injected by this tool, then exit")
    args = ap.parse_args()

    registry = load_registry()
    if len(registry) == 0:
        print("No workspaces discovered. Is USECASES_DIR mounted and populated?")
        return 2

    if args.clean_mocks:
        return clean_mocks(registry)

    backend = get_backend()
    print(f"Backend: {backend.name}  |  workspaces discovered: {len(registry)}\n")

    rows = []
    failures = 0
    for ctx in registry:
        had_data = _has_instance_data(ctx)
        mock_added = False
        if not had_data and args.mock:
            try:
                ctx.storage.write_text(MOCK_FILENAME.format(id=ctx.id), _mock_ttl(ctx.id))
                mock_added = True
            except Exception as exc:
                print(f"[{ctx.id}] could not write mock: {exc}")

        ok = False
        try:
            ok = ensure_workspace_repo(ctx)
        except Exception as exc:
            print(f"[{ctx.id}] loader raised: {exc}")

        comps = _count(backend, ctx.graphdb_repository, COMPONENT_Q) if ok else None
        attrs = _count(backend, ctx.graphdb_repository, ATTRIBUTE_Q) if ok else None
        onto_g = _count(backend, ctx.graphdb_repository, ONTOLOGY_GRAPH_Q) if ok else None

        status = "OK"
        if not ok:
            status = "LOAD-FAIL"
            failures += 1
        elif (comps or 0) == 0:
            status = "EMPTY"
            failures += 1
        elif (onto_g or 0) == 0:
            # Default graph has data but the Replica Builder / Scenario Builder
            # would report "No components found in ontology".
            status = "NO-ONTO-GRAPH"
            failures += 1

        rows.append((ctx.id, had_data, mock_added, ok, comps, attrs, onto_g, status))

    # Table
    print(f"{'workspace':<32} {'data':<5} {'mock':<5} {'load':<5} "
          f"{'comps':<6} {'attrs':<6} {'onto_g':<7} {'status':<14}")
    print("-" * 88)
    for ws_id, had, mock, ok, comps, attrs, onto_g, status in rows:
        print(f"{ws_id:<32} {'yes' if had else 'no':<5} {'yes' if mock else '-':<5} "
              f"{'ok' if ok else 'FAIL':<5} {str(comps if comps is not None else '-'):<6} "
              f"{str(attrs if attrs is not None else '-'):<6} "
              f"{str(onto_g if onto_g is not None else '-'):<7} {status:<14}")

    print()
    if failures:
        print(f"FAIL: {failures} workspace(s) did not end with queryable component data.")
        return 1
    print(f"PASS: all {len(rows)} workspaces loaded with queryable component data.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
