"""Service Requirements Builder endpoints.

A service declares which component types + attributes + links a model requires.
The palette (available components and their attributes) is read with the same
functions the Explorer uses; the requirements TTL and the service-template
YAML are generated by ``backend.service_requirements`` — the same generator
the Streamlit builder uses.
"""
from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Depends, File, HTTPException, UploadFile
from pydantic import BaseModel

from backend.service_requirements import (
    build_service_template,
    entries_from_path_tree,
    entries_from_type_tree,
    list_template_fields,
    requirements_ttl,
    service_file_id,
)
from backend.workspace import WorkspaceContext

from .deps import get_ctx, graph_client, ws_root

router = APIRouter(prefix="/api/workspaces/{workspace_id}/service", tags=["service"])

_PREFIX = "https://digicities.info/proj"


@router.get("/palette")
def palette(ctx: WorkspaceContext = Depends(get_ctx)) -> list[dict[str, Any]]:
    """Component types and their attributes — what a service can require."""
    from backend.explorer import (
        get_component_types_with_instances,
        get_component_data_unified,
        process_enhanced_component_data,
        get_visible_columns,
    )

    client = graph_client(ctx)
    types = get_component_types_with_instances(client)
    if types is None or types.empty:
        return []
    out: list[dict[str, Any]] = []
    for r in types.itertuples():
        name = str(r.componentName)
        instances, attrs = get_component_data_unified(client, name)
        cols: list[str] = []
        if instances:
            df = process_enhanced_component_data(instances, attrs)
            cols = [c for c in get_visible_columns(df) if c not in ("URI", "instance_id", "label")
                    and not c.startswith("_")]
        out.append({"component": name, "class": str(r.componentType), "attributes": cols})
    return out


@router.get("/mappings")
def mappings(ctx: WorkspaceContext = Depends(get_ctx)) -> list[dict[str, Any]]:
    """Component -> legal attributes from the ONTOLOGY (naming convention,
    with domain/range fallback) — unlike the palette, this also covers types
    with no instances yet, the common case for a brand-new partner service."""
    from backend.service_requirements.ontology import load_attribute_mappings

    try:
        mapped = load_attribute_mappings(graph_client(ctx))
    except Exception:
        mapped = {}
    return [{"component": comp, "attributes": attrs}
            for comp, attrs in sorted(mapped.items())]


class Requirement(BaseModel):
    component: str          # PascalCase class name
    attributes: list[str] = []


class Link(BaseModel):
    domain: str
    range: str


class ServiceSpec(BaseModel):
    service_name: str
    label: str = ""
    requirements: list[Requirement] = []
    links: list[Link] = []
    save: bool = True


class SvcEntry(BaseModel):
    component_type: str
    parent: str | None = None
    # A list means all-Static; a dict maps attribute -> flavors
    # (["Static", "Historic", "Live", "Future"], several allowed at once).
    attributes: list[str] | dict[str, list[str]] = []
    # Path-keyed mode (Streamlit parity): when paths are given, the YAML path
    # is the identity, so several entries of one type can coexist. All entries
    # of a request must then carry a path; parent is matched by parent_path.
    path: str | None = None
    parent_path: str | None = None


def _entries(spec_entries: list[SvcEntry]):
    if any(e.path for e in spec_entries):
        if not all(e.path for e in spec_entries):
            raise HTTPException(status_code=400,
                                detail="Either every entry carries a path, or none does.")
        paths = [e.path for e in spec_entries]
        if len(set(paths)) != len(paths):
            raise HTTPException(status_code=400, detail="Entry paths must be unique.")
        return entries_from_path_tree(
            (e.component_type, e.path or "", e.parent_path, e.attributes)
            for e in spec_entries)
    return entries_from_type_tree(
        (e.component_type, e.parent, e.attributes) for e in spec_entries)


class TemplateSpec(BaseModel):
    service_name: str
    description: str = ""
    connection: dict[str, Any] | None = None
    entries: list[SvcEntry]
    # "<path>|<attr>|<flavor>" -> user-chosen YAML field name.
    custom_field_names: dict[str, str] | None = None
    save: bool = True


@router.post("/template")
def template(spec: TemplateSpec, ctx: WorkspaceContext = Depends(get_ctx)) -> dict[str, Any]:
    """Generate the service-template YAML (connection + nested scenario_data).

    Delegates to ``backend.service_requirements`` — the same generator the
    Streamlit builder uses. Entries speak in component types by default;
    path-keyed entries (multi-instance structures) and custom field names
    are the Streamlit builder's full model.
    """
    import yaml
    if not spec.service_name.strip():
        raise HTTPException(status_code=400, detail="Give the service a name.")
    entries = _entries(spec.entries)
    doc = build_service_template(
        spec.service_name, entries,
        description=spec.description or None,
        connection=spec.connection,
        custom_field_names=spec.custom_field_names,
    )
    text = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)
    saved = None
    if spec.save:
        sid = service_file_id(spec.service_name)
        sdir = ws_root(ctx) / "services"
        sdir.mkdir(parents=True, exist_ok=True)
        (sdir / f"{sid}.yaml").write_text(text, encoding="utf-8")
        saved = f"{sid}.yaml"
    return {"yaml": text, "saved": saved}


class FieldsSpec(BaseModel):
    entries: list[SvcEntry]


@router.post("/fields")
def fields(spec: FieldsSpec, ctx: WorkspaceContext = Depends(get_ctx)) -> list[dict[str, Any]]:
    """Every customizable YAML field the current model would generate —
    the rename UI's working set. The key format matches
    ``custom_field_names``: ``<path>|<attr>|<flavor>``."""
    return [{
        "key": f"{path}|{attr}|{flavor}",
        "path": path,
        "attribute": attr,
        "flavor": flavor,
        "default_field": default_field,
        "reference": reference,
    } for path, attr, flavor, default_field, reference in list_template_fields(_entries(spec.entries))]


@router.post("/ontology/upload")
async def ontology_upload(file: UploadFile = File(...),
                          ctx: WorkspaceContext = Depends(get_ctx)) -> dict[str, Any]:
    """Parse an uploaded ontology file (.ttl/.rdf/.owl/.n3) into component
    classes + their attributes, to supplement the builder's palette — for
    partner components that exist in an ontology but not in this workspace."""
    from backend.service_requirements.ontology import parse_ontology_content

    content = await file.read()
    components, attributes = parse_ontology_content(content)
    if not components and not attributes:
        raise HTTPException(status_code=400,
                            detail="Could not parse the file as Turtle, RDF/XML, or N3 — "
                                   "or it contains no Component subclasses.")

    # Associate attributes per component via the naming convention: <Name>'s
    # attributes are the subclasses of <Name>Attribute (parse_ontology_content
    # only discovers the flat sets).
    per_component: dict[str, list[str]] = {name: [] for name in components}
    try:
        import rdflib
        from rdflib.namespace import RDFS

        g = rdflib.Graph()
        for fmt in ("turtle", "xml", "n3"):
            try:
                g.parse(data=content, format=fmt)
                break
            except Exception:
                continue
        local = lambda u: str(u).rsplit("#", 1)[-1].rsplit("/", 1)[-1]  # noqa: E731
        for name in components:
            group = [s for s in g.subjects(RDFS.subClassOf, None)
                     if local(s) == f"{name}Attribute"]
            parents = {str(s) for s in group}
            if not parents:
                continue
            todo = list(parents)
            found: list[str] = []
            while todo:
                parent = todo.pop()
                for sub in g.subjects(RDFS.subClassOf, rdflib.URIRef(parent)):
                    n = local(sub)
                    if n not in found and n != f"{name}Attribute":
                        found.append(n)
                        todo.append(str(sub))
            per_component[name] = sorted(found)
    except Exception:
        pass

    return {
        "components": [{
            "component": c.label,
            "uri": c.uri,
            "attributes": per_component.get(name, []),
        } for name, c in sorted(components.items())],
        "attribute_count": len(attributes),
    }


class ParseReq(BaseModel):
    # Parse either raw YAML text (an upload) or a saved services/ file.
    yaml: str | None = None
    file: str | None = None


@router.post("/parse")
def parse(req: ParseReq, ctx: WorkspaceContext = Depends(get_ctx)) -> dict[str, Any]:
    """Parse an existing service template back into the builder's shape —
    the load→edit→save round trip. Both nesting conventions are accepted
    (children inside ``template:`` and children as siblings), and the
    ``connection:`` block + description are preserved for re-save."""
    from backend.service_requirements.template import parse_service_template

    text = req.yaml
    if text is None:
        if not req.file:
            raise HTTPException(status_code=400, detail="Pass yaml or file.")
        p = ws_root(ctx) / "services" / req.file
        if not p.exists() or not req.file.endswith((".yaml", ".yml")):
            raise HTTPException(status_code=404, detail="service template not found")
        text = p.read_text(encoding="utf-8")
    try:
        service_name, entries, description, connection = parse_service_template(text)
    except Exception as bad_yaml:
        raise HTTPException(status_code=400, detail=f"Could not parse the template: {bad_yaml}")

    type_by_path = {e.path: e.component_type for e in entries}
    return {
        "service_name": service_name,
        "description": description,
        "connection": connection,
        "entries": [{
            "component_type": e.component_type,
            "parent": type_by_path.get(e.parent_path) or None,
            "path": e.path,
            "parent_path": e.parent_path or None,
            "level": e.level,
            "link": e.link_pattern or None,
            "attributes": e.configured_attributes,
        } for e in entries],
    }


@router.post("/requirements")
def requirements(spec: ServiceSpec, ctx: WorkspaceContext = Depends(get_ctx)) -> dict[str, Any]:
    """Requirements TTL, built with rdflib so hostile labels can't break it."""
    if not spec.service_name.strip():
        raise HTTPException(status_code=400, detail="Give the service a name.")
    ttl = requirements_ttl(
        spec.service_name,
        spec.label,
        [(r.component, r.attributes) for r in spec.requirements],
        [(l.domain, l.range) for l in spec.links],
        base=f"{_PREFIX}/{ctx.id}/services/",
    )
    saved = None
    if spec.save:
        sid = service_file_id(spec.service_name)
        sdir = ws_root(ctx) / "services"
        sdir.mkdir(parents=True, exist_ok=True)
        path = sdir / f"{sid}.ttl"
        path.write_text(ttl, encoding="utf-8")
        saved = path.name
    return {"ttl": ttl, "chars": len(ttl), "saved": saved}
